version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Docker Compose 네트워크 내에서는 서비스 이름으로 통신
      - APP_SERVICES_USER-URL=http://user-service:8081/users/{userId}
      - APP_SERVICES_PRODUCT-URL=http://product-service:8082/products/{productId}
    depends_on:
      - user-service
      - product-service

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Gateway의 라우팅 설정. environment로 주입하거나, docker용 application.yml을 별도 관리
      # 여기서는 Gateway의 application.yml에 직접 서비스 이름을 사용하도록 수정하는 것을 권장
      # e.g., uri: http://user-service:8081
    depends_on:
      - user-service
      - product-service
      - order-service
